package:
  name: pycbc-glue
  version: '0.9.8'

source:
  git_url: https://github.com/ligo-cbc/pycbc-glue.git
  git_tag: v0.9.8

build:
  detect_binary_files_with_prefix: true
  script: python setup.py install

about:
  home: 'https://github.com/ligo-cbc/pycbc-glue'
