package:
  name: metaio
  version: 8.4.0_1

source:
  git_url: git://versions.ligo.org/metaio.git
  git_tag: release-8.4.0-v1

build:
  detect_binary_files_with_prefix: true

about:
  home: 'https://www.lsc-group.phys.uwm.edu/daswg/docs/howto/lscsoft-install.html'
