# Run this file using `conda build -c moble .`

package:
  name: lalsuite
  version: 6.37

source:
  git_url: git://versions.ligo.org/lalsuite.git
  git_tag: lalsuite-v6.37

requirements:
  build:
    - python
    - numpy
    - h5py
    - scipy
    - cython
    - swig
    - gsl
    - libframe
    - metaio

build:
  detect_binary_files_with_prefix: true

about:
  home: 'https://www.lsc-group.phys.uwm.edu/daswg/docs/howto/lscsoft-install.html'
