package:
  name: pycbc
  version: '1.4.1'

source:
  git_url: https://github.com/ligo-cbc/pycbc.git
  git_tag: v1.4.1
  patches:
    - patches.txt

build:
  detect_binary_files_with_prefix: true
  script: python setup.py install

requirements:
  build:
    - lalsuite
    - pycbc-glue
    - pycbc-pylal
    - werkzeug
    - flask
    - jinja2
    - wtforms
    - requests
    - markupsafe
    - itsdangerous
    - boto
    - pyopenssl
    - mako
    - decorator
    - scipy
    - matplotlib
    - numpy
    - pillow
    - h5py
    - jinja2
    - mpld3
    # - Flask-SQLAlchemy
    # - Flask-Cache
    # - pam
    # - plex
    # - pyRXP

about:
  home: 'https://github.com/ligo-cbc/pycbc'
