package:
  name: pycbc
  version: '1.4.1'

source:
  git_url: https://github.com/ligo-cbc/pycbc.git
  git_tag: v1.4.1

build:
  detect_binary_files_with_prefix: true
  script: python setup.py install

requirements:
  build:
    - lalsuite

about:
  home: 'https://github.com/ligo-cbc/pycbc'
