package:
  name: pycbc-pylal
  version: '0.9.6'

source:
  git_url: https://github.com/ligo-cbc/pycbc-pylal.git
  git_tag: v0.9.6

build:
  detect_binary_files_with_prefix: true
  script: python setup.py install

requirements:
  build:
    - lalsuite

about:
  home: 'https://github.com/ligo-cbc/pycbc-pylal'
