package:
  name: gsl
  version: 1.16

source:
  fn: gsl-1.16.tar.gz
  md5: e49a664db13d81c968415cd53f62bc8b
  url: ftp://ftp.gnu.org/gnu/gsl/gsl-1.16.tar.gz

build:
  detect_binary_files_with_prefix: true

about:
  home: 'http://www.gnu.org/software/gsl/'
  license: GPL
  summary: 'The GNU Scientific Library (GSL) is a numerical library for C and C++ programmers'
